neo4juser_debug_email:
    pattern:  /neo4juser/debug/finduserbyemail/{email}
    defaults: { _controller: Neo4jUserBundle:Debug:finduserbyemail }
    requirements:
        _method:  GET      
        
neo4juser_debug_id:
    pattern:  /neo4juser/debug/finduserbyid/{id}
    defaults: { _controller: Neo4jUserBundle:Debug:finduserbyid }
    requirements:
        _method:  GET        
